# Jim; Copied this off stack overflow. Not sure about this, does seem to ignore my failing unite tests... Give up!
# Also, I can't get it to run automatically - it can only be triggered from the UI. Shouldn't it run on every commit
# or something?
name: CI pipeline
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn --no-transfer-progress -B compile --file pom.xml
      - name: Tests with Maven
        run: mvn -B test --file pom.xml
